project_data_root: 'C:\Users\oscar\OneDrive\Escritorio\SOURCES TGF\mi_proyecto'
local_db_dir: 'D:\tfg_finance\mi_proyecto_datos\local_db'
processed_dir: 'D:\tfg_finance\mi_proyecto_datos\local_db\processed'